### ISSUE TITLE
411 Length Required when trying to use minio as Cloud Foundry Blobstore

### ISSUE THREAD

**Issue by rkoster** [minio/minio-boshrelease#5]
I have configure cloud foundry with the following ops file:
```yaml
# Configure CC to use minio 
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/buildpacks
  value:
    blobstore_type: fog
    buildpack_directory_key: buildpacks
    fog_connection: &fog_connection
      endpoint: http://any.minio.default.cf.bosh:9000
      aws_access_key_id: "((minio_accesskey))"
      aws_secret_access_key: "((minio_secretkey))"
      path_style: true
      provider: AWS
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/droplets
  value:
    blobstore_type: fog
    buildpack_directory_key: droplets
    fog_connection: *fog_connection
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/packages
  value:
    blobstore_type: fog
    buildpack_directory_key: packages
    fog_connection: *fog_connection
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/resource_pool
  value:
    blobstore_type: fog
    buildpack_directory_key: resource_pool
    fog_connection: *fog_connection
```

And I get the following error message in the post-start log from the cloud-controller:
```
[2017-04-18 14:41:27+0000] Excon::Error::LengthRequired: Expected(200) <=> Actual(411 Length Required)
[2017-04-18 14:41:27+0000] excon.error.response
[2017-04-18 14:41:27+0000]   :body          => "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>MissingContentLength</Code><Message>You must provide the Content-Length HTTP header.</Message><Key></Key><BucketName></BucketName><Resource>/buildpacks/d4/96/d496f639-c268-4636-bba1-c965cf2d2ca2_15ca52b99ee13b1176a8d5b0d12d8a241b59fa569a5e4009f19a0e4bfe2a54b4</Resource><RequestId>3L137</RequestId><HostId>3L137</HostId></Error>"
[2017-04-18 14:41:27+0000]   :cookies       => [
[2017-04-18 14:41:27+0000]   ]
[2017-04-18 14:41:27+0000]   :headers       => {
[2017-04-18 14:41:27+0000]     "Accept-Ranges"    => "bytes"
[2017-04-18 14:41:27+0000]     "Content-Type"     => "application/xml"
[2017-04-18 14:41:27+0000]     "Date"             => "Tue, 18 Apr 2017 14:41:27 GMT"
[2017-04-18 14:41:27+0000]     "Server"           => "Minio/RELEASE.2017-03-16T21-50-32Z (linux; amd64)"
[2017-04-18 14:41:27+0000]     "Vary"             => "Origin"
[2017-04-18 14:41:27+0000]     "X-Amz-Request-Id" => "14B684EEC4908FD9"
[2017-04-18 14:41:27+0000]   }
[2017-04-18 14:41:27+0000]   :host          => "any.minio.default.cf.bosh"
[2017-04-18 14:41:27+0000]   :local_address => "10.24.0.70"
[2017-04-18 14:41:27+0000]   :local_port    => 50544
[2017-04-18 14:41:27+0000]   :path          => "/buildpacks/d4/96/d496f639-c268-4636-bba1-c965cf2d2ca2_15ca52b99ee13b1176a8d5b0d12d8a241b59fa569a5e4009f19a0e4bfe2a54b4"
[2017-04-18 14:41:27+0000]   :port          => 9000
[2017-04-18 14:41:27+0000]   :reason_phrase => "Length Required"
[2017-04-18 14:41:27+0000]   :remote_ip     => "10.24.0.86"
[2017-04-18 14:41:27+0000]   :status        => 411
[2017-04-18 14:41:27+0000]   :status_line   => "HTTP/1.1 411 Length Required\r\n"
[2017-04-18 14:41:27+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/excon-0.54.0/lib/excon/middlewares/expects.rb:7:in `response_call'
[2017-04-18 14:41:27+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/excon-0.54.0/lib/excon/middlewares/response_parser.rb:9:in `response_call'
[2017-04-18 14:41:27+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/excon-0.54.0/lib/excon/connection.rb:388:in `response'
[2017-04-18 14:41:27+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/excon-0.54.0/lib/excon/connection.rb:252:in `request'
[2017-04-18 14:41:27+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/fog-core-1.43.0/lib/fog/core/connection.rb:81:in `request'
```

**Comment by rkoster** [comment]
Was able to reproduce the issue with plain `fog` by following the [code path from the Cloud Controller](https://github.com/cloudfoundry/cloud_controller_ng/blob/master/lib/cloud_controller/blobstore/fog/fog_client.rb#L57-L73):
```ruby
s3 = Fog::Storage::AWS.new(
  aws_access_key_id: '{key}', 
  aws_secret_access_key: '{secret}', 
  endpoint: 'http://any.minio.default.cf.bosh:9000', 
  path_style: true
)
IO.write('/tmp/foo', 'bar')
dir = s3.directories.get('test', { max_keys: 1 })
files = dir.files
files.create(
  key: SecureRandom.hex, 
  body: File.open('/tmp/foo'), 
  content_type: 'application/zip', 
  public: false
)
```

Also found a potential fix:
```ruby
files.create(
  key: SecureRandom.hex, 
  body: File.open('/tmp/foo').path, 
  content_type: 'application/zip', 
  public: false
)
```

**Comment by rkoster** [comment]
above 'fix' is just setting the body to the path string

**Comment by rkoster** [comment]
When setting `ENV['EXCON_DEBUG'] = '1'`:

working request with `body: 'foo'`
```
  :expects             => 200
  :headers             => {
    "Authorization"        => "REDACTED"
    "Content-Length"       => 3
    "Content-Type"         => "application/zip"
    "Host"                 => "any.minio.default.cf.bosh"
    "User-Agent"           => "fog-core/1.43.0"
    "x-amz-acl"            => "private"
    "x-amz-content-sha256" => "2c26b46b68ffc68ff99b453c1d30413413422d706483bfa0f98a5e886266e7ae"
    "x-amz-date"           => "20170419T094619Z"
  }
  :host                => "any.minio.default.cf.bosh"
  :hostname            => "any.minio.default.cf.bosh"
  :idempotent          => true
  :instrumentor        => Excon::StandardInstrumentor
  :instrumentor_name   => "excon"
  :method              => "PUT"
```

failed request with `body: File.open('/tmp/foo')`
```
  :expects             => 200
  :headers             => {
    "Authorization"                => "REDACTED"
    "Content-Type"                 => "application/zip"
    "Host"                         => "any.minio.default.cf.bosh"
    "Transfer-Encoding"            => "chunked"
    "User-Agent"                   => "fog-core/1.43.0"
    "x-amz-acl"                    => "private"
    "x-amz-content-sha256"         => "STREAMING-AWS4-HMAC-SHA256-PAYLOAD"
    "x-amz-date"                   => "20170419T094955Z"
    "x-amz-decoded-content-length" => 4
  }
  :host                => "any.minio.default.cf.bosh"
  :hostname            => "any.minio.default.cf.bosh"
  :idempotent          => true
  :instrumentor        => Excon::StandardInstrumentor
  :instrumentor_name   => "excon"
  :method              => "PUT"
```

**Comment by rkoster** [comment]
Fixed by switching to `aws_signature_version: 2`

**Comment by donatello** [comment]
@rkoster The signature issue that you had is fixed in current master of Minio, and the next release would have the fix.

Do you happen to have tried using Minio as a blobstore for BOSH? I would like to add this support or document this if it is already possible. Any pointers would be welcome.

**Comment by rkoster** [comment]
I'm currently working on [using minio as blobstore for Cloud Foundry](https://github.com/cloudfoundry/cf-deployment/pull/132) It almost works. Blobstore support for BOSH is probably less usefull at this point since the BOSH director is still a single point of failure, so even with minio your BOSH would still not be HA. But with switching CF to use minio we would be able to eliminate the last SPF for CF without relying on non BOSH deployed infrastructure (for example using a Netapp provided NFS).

**Comment by abhilash07** [comment]
@rkoster thanks for you post, it is most needed and waited service for CF,
I am trying to configure minio object storge i found your post, https://github.com/cloudfoundry/cf-deployment/pull/132, is there any update on you testing.

i have curio, did we want to change any source code in open source cloud_controller_ng, fog_client ???

**Comment by rkoster** [comment]
@abhilash07 I have not used minio with cf recently, but nothing should prevent you from testing the ops-file from the linked PR.

**Comment by abhilash07** [comment]
@rkoster thanks for your response

**Comment by abhilash07** [comment]
@rkoster, i have tried minio for cf blobstore. But unfortunately i encountered below error.

![screen shot 2018-05-04 at 2 25 36 pm](https://user-images.githubusercontent.com/10971841/39614047-83d0d27a-4fa7-11e8-98c3-a2ced4c3be6c.png)

[cf-deployment.txt](https://github.com/minio/minio-boshrelease/files/1973336/cf-deployment.txt)
[deployment-vars.txt](https://github.com/minio/minio-boshrelease/files/1973337/deployment-vars.txt)

after checking the cloud_controller_ng post-sart log i found this error. 

"rake aborted!
[2018-05-04 05:04:41+0000] CloudController::Blobstore::BlobstoreError: Connection refused - connect(2) for 10.244.0.34:443 (Errno::ECONNREFUSED)"

[post-start.stderr.log](https://github.com/minio/minio-boshrelease/files/1973345/post-start.stderr.log)

Do you any idea about this error.

Thanks in advance.

**Comment by abhilash07** [comment]
@krishnasrinivas did you tried Minio Blobstore for cloud foundry blobstore ???
